config/routes.rb
Postmarks::Application.routes.draw do
  get 'signup' => 'users#new' 
  get 'login' => 'sessions#new' 
  get 'logout' => 'sessions#destroy'

  post 'login' => 'sessions#create'
  post '/email_processor' => 'griddler/emails#create'
  

  get 'about' => 'welcome#about'
  get 'tags/:tag', to: 'bookmarks#index', as: :tag

  get 'profile' => 'users#show'

  resources :users, only: [:show, :create] #route for users#show
  resources :sessions, only: [:create, :new]

  resources :favorites, only: [:index]
  resources :bookmarks, only: [:index, :create, :show, :update, :destroy, :edit] do
    match '/up-vote', to: 'votes#up_vote', as: :up_vote
    match '/down-vote', to: 'votes#down_vote', as: :down_vote
    resources :favorites, only: [:create, :destroy]
  end

  root :to => 'welcome#index' 

  

   

end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
   attr_accessible :title, :body, :tag_list, :url, :thumbnail_url
   acts_as_taggable
   
   has_many :votes, dependent: :destroy
   has_many :favorites, dependent: :destroy

   before_create :set_initial_rank
   before_save :save_embedly_data

   default_scope order('rank DESC')
   # scope :visible_to, lambda { |user| user ? scoped : joins(:bookmark).where('bookmark.favorited' => true) }

   belongs_to :user


   def save_embedly_data
      embedly = Embedly::API.new.oembed( url: self.url).first
      self.thumbnail_url = embedly.thumbnail_url
      self.title = embedly.title
   end

   def up_votes
      self.votes.where(value: 1).count
   end

   def down_votes
      self.votes.where(value: -1).count
   end

   def points
      self.votes.sum(:value).to_i     
   end 

   def update_rank
      # age = (self.created_at - Time.new(1970,1,1)) / 86400
      new_rank = points 

      self.update_attribute(:rank, new_rank)
   end

   private

   # Possible alternative: after_create, create a +1 vote for the User the Bookmark belongs to
   # (forcing rank update)
   def set_initial_rank
      self.rank = 0
   end

   def create_vote
      self.user.votes.create(value: 1, bookmark: self)
   end

   
   # def thumbnail_url
   # 		Embedly::API.new.oembed( url: self.url).first.thumbnail_url
   # end

   # def title_url
   # 		Embedly::API.new.oembed( url: self.url).first.title
   # end

   # def description_url
   # 		Embedly::API.new.oembed( url: self.url).first.description
   # end

end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
	before_filter :authorize, only: [:edit, :update, :destroy]
	
	def index
		if params[:tag]
			@bookmarks = Bookmark.tagged_with(params[:tag])
		else
			@bookmarks = Bookmark.all 
		end
	end

	def show
		@bookmark = Bookmark.find(params[:id])
	end

	def new
		@bookmark = Bookmark.new
	end

	def edit
		@bookmark = Bookmark.find(params[:id])
	end

	def create
		@bookmark = Bookmark.new(params[:bookmark])
		@bookmark.user = current_user
		if @bookmark.save
			redirect_to bookmarks_path, notice: "Bookmark was saved successfully"
		else
			flash[:error] =  "There was an error creating the bookmark"
			render new
		end
	end

	def update
		@bookmark = Bookmark.find(params[:id])
		if @bookmark.update_attributes(params[:bookmark])
			redirect_to bookmarks_path, notice: "Bookmark was updated successfully."
		else
			flash[:error] = "There was error updating the Bookmark, not sure what though"
			render :edit
		end
	end

	def destroy
		@bookmark = Bookmark.find(params[:id])
		name = @bookmark.title

    if @bookmark.destroy
      flash[:notice] = "\"#{name}\" bookmark was deleted successfully."
      redirect_to bookmarks_path
    else
      flash[:error] = "There was an error deleting the topic."
      render :index
    end

	end


end

app/helpers/bookmark_helper.rb
module BookmarkHelper

	def tag_link
		raw bookmark.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') 
	end 

end

app/views/bookmarks/_bookmark.html.erb
<div class="item">
  <div class="box panel panel-default">
  	<div class="panel-heading">
		<% if bookmark.url %>
			<!--#Title-->
			<strong><%= bookmark.title %></strong><br/>
			<%= link_to image_tag(bookmark.thumbnail_url, :size => "250x250" ), bookmark.url%><br/>
		<% end %>
	</div>
		

		<%= render partial: 'votes/voter', locals: {bookmark: bookmark} %>

		<!--#Description-->
		<!--<%= bookmark.user %>-->
		[<%=	bookmark.body %>]
		<!--#tags-->

		
		<p>Tags: <%= raw bookmark.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></p>
		<!--#links-->
		<p>
			<%= link_to "Edit", edit_bookmark_path(bookmark) %> 
			<%= link_to "Delete", bookmark, method: :delete, confirm: 'Are you sure you want to delete this post?' %>
			<%= render partial: 'favorites/favorite', locals: {bookmark: bookmark} %>
			
		</p>
	</div>
</div>

app/views/bookmarks/_form.html.erb
<%= form_for bookmark do |f| %>

  <form role="form">
    <!--<div class="form-group">
      <%= f.label :title %>
      <div class="controls">
        <%= f.text_field :title, placeholder: "Every bookmark needs a name", class: 'form-control' %>
      </div>
    </div>-->

    <div class="control-group">
      <%= f.label :url, "Add link here" %>
      <div class="controls">
        <%= f.text_field :url, placeholder: "'Must include 'http://'", class: 'form-control' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :notes %>
      <div class="controls">
        <%= f.text_area :body, rows: 4, placeholder: "Briefly describe the bookmark here", class: 'form-control' %>
      </div>
    </div></br>

    <div class="control-group">
      <%= f.label :tag_list, "Tags (seperated by commas)" %>
      <div class="controls">
        <%= f.text_field :tag_list, placeholder: "Fun, Food, Lettuce", class: 'form-control' %>
      </div>
    </div>
    </br>

    <div class="control-group">
      <div class="controls">
        <%= f.submit "Save", class: 'btn-primary' %>
      </div>
    </div>
  </form>

<% end %>

app/views/bookmarks/edit.html.erb
<h1>Edit Topic</h1>

<div>
<%= link_to 'Back to bookmarks', bookmarks_path %>
</div>

<%= form_for @bookmark do |f| %>

  <form role="form">
    <div class="form-group">
      <%= f.label :title %>
      <div class="controls">
        <%= f.text_field :title, placeholder: "Every bookmark needs a name", class: 'form-control' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :url, "Add link here" %>
      <div class="controls">
        <%= f.text_field :url, placeholder: "'http:// is required'", class: 'form-control' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :body %>
      <div class="controls">
        <%= f.text_area :body, rows: 4, class: 'form-control' %>
      </div>
    </div></br>
    <div class="control-group">
      <%= f.label :tag_list, "Tags (seperated by commas)" %>
      <div class="controls">
        <%= f.text_field :tag_list, class: 'form-control' %>
      </div>
    </div>
    </br>
    <div class="control-group">
      <div class="controls">
        <%= f.submit "Save", class: 'btn-primary' %>
      </div>
    </div>
  </form>

<% end %>

app/views/bookmarks/index.html.erb
<div class="jumbotron">
	<% tag_cloud Bookmark.tag_counts, %w{s m l} do |tag, css_class| %>
		<%= link_to '#' + tag.name, tag_path(tag.name), class: css_class %>
	<% end %>
</div>

	<div id="container" class="js-masonry" data-masonry-options='{ "columnWidth": 2, "itemSelector": ".item" }'>
		<%= render @bookmarks %>
	</div>
		
<div>
<hr/>
	<% #if current_user %>
	<%= render partial: 'form', locals: { bookmark: Bookmark.new } %>
	<% #end %>
</div>