config/routes.rb
Postmarks::Application.routes.draw do
  get 'signup' => 'users#new' 
  get 'login' => 'sessions#new' 
  get 'logout' => 'sessions#destroy'

  post 'login' => 'sessions#create'
  post '/email_processor' => 'griddler/emails#create'
  

  get 'about' => 'welcome#about'
  get 'tags/:tag', to: 'bookmarks#index', as: :tag

  get 'profile' => 'users#show'

  resources :users, only: [:show, :create] #route for users#show
  resources :sessions, only: [:create, :new]

  resources :favorites, only: [:index]
  resources :bookmarks, only: [:index, :create, :show, :update, :destroy, :edit] do
    match '/up-vote', to: 'votes#up_vote', as: :up_vote
    match '/down-vote', to: 'votes#down_vote', as: :down_vote
    resources :favorites, only: [:create, :destroy]
  end

  root :to => 'welcome#index' 

  

   

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Postmarks</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "http://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/3.0.4/jquery.imagesloaded.min.js" %>
  <%= javascript_include_tag "http://cdnjs.cloudflare.com/ajax/libs/masonry/3.1.2/masonry.pkgd.min.js" %>
  <%= csrf_meta_tags %>
</head>

<body>
 <div class="container">
  <div class="navbar">
    <div class="navbar-inner">
      <ul class="nav nav-tabs">
        
        <li><%= link_to "Postmarks", "#" %></li>
        <li><%= link_to "View Bookmarks", bookmarks_path  %></li>
        <% if current_user %>
        <li><%= link_to "Favorited Bookmarks", favorites_path %></li>
        <li><%= link_to "My Bookmarks", profile_path %></li>
        <% end %>


        <div class="pull-right">
          <% if current_user %>
            Logged in as <%= link_to (current_user.name || current_user.email), current_user %>.
            <%= link_to "Log Out", logout_path %>
          <% else %>
            <%= link_to "Sign Up", signup_path %> or
            <%= link_to "Log In", login_path %>
          <% end %>
        </div>
      </ul>
      
    </div>
  </div>

    <% if flash[:notice] %>
      <div class="alert alert-success alert-dismissable">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:error] %>
      <div class="alert alert-error alert-dismissable">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:error] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-dismissable">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>
  <%= yield %>
</div>
</body>
</html>